C     **  EXAMPLE PROGRAM 14.12
C     **  SUBROUTINE FOR FINDING THE ROOT OF AN EQUATION BY
C     **  NEWTON-RAPHSON METHOD. FUNCN IS THE FUNCTION NAME.
C     **  XINL IS THE INITIAL TRIAL ROOT.
C     **  DFUNC IS THE DERIVATIVE OF THE FUNCTION FUNC.
C     **  EPS IS THE PRESCRIBED ERROR LIMIT OF THE ROOT.
C     **  MAXIT IS THE MAXIMUM NUMBER OF ITERATIONS ALLOWED.
C     **  INDIC IS AN INDICATOR SET TO 1 IF THERE IS NO
C     **  CONVERGENCE IN MAXIT ITERATIONS.
C     **  THE ROOT IS RETURNED IN SOLN.
C     ______________________________________________________
      SUBROUTINE ROOT (FUNCN,DFUNCN,XINL,EPS,MAXIT,INDIC,SOLN)
      INDIC = 0
      DO 100 I=1,MAXIT
         F0 = FUNCN (XINL)
         DF0 = DFUNCN (XINL)
         XNEW = XINL - (F0/DF0)
         IF (ABS((XNEW-XINL)/XNEW) .LE. EPS) GO TO 120
         XINL = XNEW
 100  CONTINUE
 101  INDIC = 1
      SOLN = XNEW
      RETURN
 120  SOLN = XNEW
      RETURN
      END
